### ISSUE TITLE
Scrolling in both directions?

### ISSUE THREAD

**Issue by blissdev** [HenrikBechmann/react-infinite-grid-scroller#15]
Is it possible to set this up to scroll in both X and Y directions?

**Comment by HenrikBechmann** [comment]
Not two directions of infinite scroll at the same level. However you can have nested scrollers, so you can have the main scroller vertical, and nested scrollers horizontal. They wouldn't be coordinated though. I suppose with some work you could co-ordinate them with multiple gotoIndex api calls.

Also you can oversize cells. So if you have the main scroller cells at a width of say, 4000px, and nested horizontal scrollers that have just the right number of cells to fit in that width (ie they wouldn't need to scroll) you could mimic a kind of spreadsheet feel with co-ordinated rows.

**Comment by blissdev** [comment]
I see, thank you.
