### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by ahmafi** [HenrikBechmann/react-infinite-grid-scroller#19]
Hi, I'm trying to use this library with next.js, but it produces this error after just importing the library.

```js
import Scroller from 'react-infinite-grid-scroller';
```

```
export default Scroller.default
^^^^^^

SyntaxError: Unexpected token 'export'
   at Object.compileFunction (node:vm:352:18)
   at wrapSafe (node:internal/modules/cjs/loader:1033:15)
   at Module._compile (node:internal/modules/cjs/loader:1069:27)
   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
   at Module.load (node:internal/modules/cjs/loader:981:32)
   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
   at Module.require (node:internal/modules/cjs/loader:1005:19)
   at require (node:internal/modules/cjs/helpers:102:18)
```

![image](https://user-images.githubusercontent.com/12560109/208653275-89f69bb2-4efd-44d6-b73b-b62a50030c3e.png)

**Comment by HenrikBechmann** [comment]
Thanks for the feedback @ahmafi. 

Sorry, I don't recognize any of the names in the error message you got, and I see that you're showing a peer conflict with react 16 (I'm using react 18). I'd suggest you examine the [package.json](https://github.com/HenrikBechmann/react-infinite-grid-scroller/blob/staging/package.json) list of versions.

Also, does next support react portals? (I'm not familiar with next). Portals are integral to this package.

**Comment by HenrikBechmann** [comment]
Well, from [this](https://dev.to/ataparvinghods/react-portals-and-how-to-use-them-next-js-and-cra-2dic) I take it that next supports portals...

**Comment by ahmafi** [comment]
> Thanks for the feedback @ahmafi.
> 
> Sorry, I don't recognize any of the names in the error message you got, and I see that you're showing a peer conflict with react 16 (I'm using react 18). I'd suggest you examine the [package.json](https://github.com/HenrikBechmann/react-infinite-grid-scroller/blob/staging/package.json) list of versions.
> 
> Also, does next support react portals? (I'm not familiar with next). Portals are integral to this package.

Oh, sorry, the installation warnings are related to other packages. I'll remove them from OP.

**Comment by ahmafi** [comment]
I think [this](https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export) might help.

**Comment by HenrikBechmann** [comment]
Yeah RIGS compiles to ES2015
