### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by bunyaminmrcn** [HenrikBechmann/react-infinite-grid-scroller#23]
Hi.
I am using next.js(client side) and using react-infinite-grid-scroller (RIGS).
But I had some error that happened when rendering
` ReferenceError: self is not defined`

**Comment by bunyaminmrcn** [comment]
Screenshot is here.
![Screenshot from 2024-09-13 09-38-54](https://github.com/user-attachments/assets/20787091-a7cc-4259-8a7e-7a107aa9d7c4)

**Comment by HenrikBechmann** [comment]
There's no `self` variable in my code.

Guessing some kind of incompatibility between webpack build and next...
