### ISSUE TITLE
How to render preload data.

### ISSUE THREAD

**Issue by bunyaminmrcn** [HenrikBechmann/react-infinite-grid-scroller#24]
Hi. This is a question about your library.  I didn't understand how to works.
I want to render custom preloaded data like this. 

[gist repo](https://gist.github.com/bunyaminmrcn/3df850748b69c54f2251cd8b5c81f219)

How to pass data , renderItem to GridScroller

**Comment by HenrikBechmann** [comment]
Preload behaves as though the entire list was scrolled and saved in memory.

I suggest you start with defaults to get used to listing individual items, then try preload mode.
